// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5JKGm8FgVdlXF4PXnz3bf8Kb3tet7SVI',
    appId: '1:1021774328595:web:debd8775b0dc3e146c60e6',
    messagingSenderId: '1021774328595',
    projectId: 'chatapp-e53d8',
    authDomain: 'chatapp-e53d8.firebaseapp.com',
    storageBucket: 'chatapp-e53d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6YjJp_JBdUyn2uBYtnfx44amJfDjPZ7s',
    appId: '1:1021774328595:android:d466dc17084fb23c6c60e6',
    messagingSenderId: '1021774328595',
    projectId: 'chatapp-e53d8',
    storageBucket: 'chatapp-e53d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8GbQO9k_XGQb151AsHGdGzsM-1ZhzTf8',
    appId: '1:1021774328595:ios:347c3dd622934f396c60e6',
    messagingSenderId: '1021774328595',
    projectId: 'chatapp-e53d8',
    storageBucket: 'chatapp-e53d8.appspot.com',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8GbQO9k_XGQb151AsHGdGzsM-1ZhzTf8',
    appId: '1:1021774328595:ios:347c3dd622934f396c60e6',
    messagingSenderId: '1021774328595',
    projectId: 'chatapp-e53d8',
    storageBucket: 'chatapp-e53d8.appspot.com',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5JKGm8FgVdlXF4PXnz3bf8Kb3tet7SVI',
    appId: '1:1021774328595:web:61911e602a666daa6c60e6',
    messagingSenderId: '1021774328595',
    projectId: 'chatapp-e53d8',
    authDomain: 'chatapp-e53d8.firebaseapp.com',
    storageBucket: 'chatapp-e53d8.appspot.com',
  );

}